title: 98548J Notebook
description: This webpage contains the engineering notebook for the VRC team 98548J.
theme: just-the-docs

color_scheme: modifications
search_enabled: true
favicon_ico: "/assets/engineering/Fedora.ico"

callouts:
  problem:
    title: "The Problem"
    color: red
  decision:
    title: "The Decision"
    color: yellow
  note:
    title: "note"
    color: grey-lt
  grey-lt:
    title: "Meeting Template"
    color: grey-lt
  takeaway:
    title: "The Takeaway"
    color: grey-lt

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
      
compress_html:
  ignore:
    envs: all

defaults:
  - scope:
      path: "docs"
    values:
      layout: "doc"

url: https://notcalebcarlson.github.io/98548J

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
